baseURL = "https://reference.groupdocs.com/viewer"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-WZTNN8"

[[deployment.targets]]
name = "Production"
URL = "s3://tutorials.groupdocs.com/?prefix=viewer/&region=us-west-2"
